author: Mohammad Hossein Salari
# for a normal use at the base of the server change it to "/"

#baseurl: /
url: 

title: Mohammad Hossein Salari's Resume
name: Mohammad Hossein Salari
email: mh.salari[@]sutech.ac.ir
email_full: mailto:mh.salari@sutech.ac.ir
website: mh-salari.me
website_full: http://mh-salari.me
github: mh-salari
#twitter: mh_salari
tel: +98 917-804-4665
tel_full: tel:+989178044665
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: Teharn,iran
#postcode: EH3 5BL
city: shiraz
country: Iran
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
